In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [2]:
df=pd.DataFrame({
    "soil_moisture":[0.10,0.15,0.20,0.25,0.40,0.60,0.35,0.18,0.45,0.05,0.80,0.27,0.55,0.70,0.12,0.30],
    "temperture_c":[34,30,26,22,28,30,19,22,35,24,33,33,21,25,20,29],
    "sunlight__hours":[9,8,7,4,8,10,3,10,12,5,9,11,2,6,1,9],
    "needs_water":[1,1,1,0,0,0,0,1,0,1,0,1,0,0,1,1]
})

In [3]:
df

    soil_moisture  temperture_c  sunlight__hours  needs_water
0            0.10            34                9            1
1            0.15            30                8            1
2            0.20            26                7            1
3            0.25            22                4            0
4            0.40            28                8            0
5            0.60            30               10            0
6            0.35            19                3            0
7            0.18            22               10            1
8            0.45            35               12            0
9            0.05            24                5            1
10           0.80            33                9            0
11           0.27            33               11            1
12           0.55            21                2            0
13           0.70            25                6            0
14           0.12            20                1            1
15           0.30            29                9            1

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   soil_moisture    16 non-null     float64
 1   temperture_c     16 non-null     int64
 2   sunlight__hours  16 non-null     int64
 3   needs_water      16 non-null     int64
dtypes: float64(1), int64(3)
memory usage: 644.0 bytes

In [5]:
df.describe()

       soil_moisture  temperture_c  sunlight__hours  needs_water
count      16.000000     16.000000        16.000000    16.000000
mean        0.341875     26.937500         7.125000     0.500000
std         0.224298      5.297405         3.304038     0.516398
min         0.050000     19.000000         1.000000     0.000000
25%         0.172500     22.000000         4.750000     0.000000
50%         0.285000     27.000000         8.000000     0.500000
75%         0.475000     30.750000         9.250000     1.000000
max         0.800000     35.000000        12.000000     1.000000

In [6]:
X=df[["soil_moisture","temperture_c","sunlight__hours"]]
y=df['needs_water']

In [7]:
df.columns

Index(['soil_moisture', 'temperture_c', 'sunlight__hours', 'needs_water'], dtype='str')

In [8]:
X

    soil_moisture  temperture_c  sunlight__hours
0            0.10            34                9
1            0.15            30                8
2            0.20            26                7
3            0.25            22                4
4            0.40            28                8
5            0.60            30               10
6            0.35            19                3
7            0.18            22               10
8            0.45            35               12
9            0.05            24                5
10           0.80            33                9
11           0.27            33               11
12           0.55            21                2
13           0.70            25                6
14           0.12            20                1
15           0.30            29                9

In [9]:
X_min=X.min()
X_max=X.max()
X_scaled=(X-X_min)/(X_max-X_min +1e-8)

In [10]:
X_scaled

    soil_moisture  temperture_c  sunlight__hours
0        0.066667        0.9375         0.727273
1        0.133333        0.6875         0.636364
2        0.200000        0.4375         0.545455
3        0.266667        0.1875         0.272727
4        0.466667        0.5625         0.636364
5        0.733333        0.6875         0.818182
6        0.400000        0.0000         0.181818
7        0.173333        0.1875         0.818182
8        0.533333        1.0000         1.000000
9        0.000000        0.3125         0.363636
10       1.000000        0.8750         0.727273
11       0.293333        0.8750         0.909091
12       0.666667        0.1250         0.090909
13       0.866667        0.3750         0.454545
14       0.093333        0.0625         0.000000
15       0.333333        0.6250         0.727273

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42,stratify=y)

In [12]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [13]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [14]:
history=model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=4,verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 194ms/step - accuracy: 0.5000 - loss: 0.8080 - val_accuracy: 0.5000 - val_loss: 0.8170
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.8032 - val_accuracy: 0.5000 - val_loss: 0.8138
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7980 - val_accuracy: 0.5000 - val_loss: 0.8108
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7930 - val_accuracy: 0.5000 - val_loss: 0.8081
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7890 - val_accuracy: 0.5000 - val_loss: 0.8055
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7858 - val_accuracy: 0.5000 - val_loss: 0.8027
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7824 - val_accuracy: 0.5000 - val_loss: 0.7999
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7786 - val_accuracy: 0.5000 - val_loss: 0.7972
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7763 - val_accuracy: 0.5000 - val_loss: 0.7952
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.7733 - val_accuracy: 0.2500 - val_loss: 0.7935
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7712 - val_accuracy: 0.2500 - val_loss: 0.7921
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7697 - val_accuracy: 0.2500 - val_loss: 0.7906
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7681 - val_accuracy: 0.2500 - val_loss: 0.7892
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7676 - val_accuracy: 0.2500 - val_loss: 0.7879
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7644 - val_accuracy: 0.2500 - val_loss: 0.7865
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7626 - val_accuracy: 0.2500 - val_loss: 0.7853
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.7620 - val_accuracy: 0.2500 - val_loss: 0.7840
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.7600 - val_accuracy: 0.2500 - val_loss: 0.7828
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7583 - val_accuracy: 0.2500 - val_loss: 0.7816
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7564 - val_accuracy: 0.2500 - val_loss: 0.7804
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7545 - val_accuracy: 0.2500 - val_loss: 0.7791
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7532 - val_accuracy: 0.2500 - val_loss: 0.7778
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7520 - val_accuracy: 0.2500 - val_loss: 0.7765
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7504 - val_accuracy: 0.2500 - val_loss: 0.7753
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.7492 - val_accuracy: 0.2500 - val_loss: 0.7740
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.7479 - val_accuracy: 0.2500 - val_loss: 0.7728
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7468 - val_accuracy: 0.2500 - val_loss: 0.7716
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7455 - val_accuracy: 0.2500 - val_loss: 0.7704
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7444 - val_accuracy: 0.2500 - val_loss: 0.7692
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7433 - val_accuracy: 0.2500 - val_loss: 0.7681
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7418 - val_accuracy: 0.2500 - val_loss: 0.7669
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7414 - val_accuracy: 0.2500 - val_loss: 0.7658
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7413 - val_accuracy: 0.2500 - val_loss: 0.7647
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.7391 - val_accuracy: 0.2500 - val_loss: 0.7636
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7384 - val_accuracy: 0.2500 - val_loss: 0.7625
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7373 - val_accuracy: 0.2500 - val_loss: 0.7614
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7364 - val_accuracy: 0.2500 - val_loss: 0.7604
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7365 - val_accuracy: 0.2500 - val_loss: 0.7593
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7349 - val_accuracy: 0.2500 - val_loss: 0.7583
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7338 - val_accuracy: 0.2500 - val_loss: 0.7573
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7326 - val_accuracy: 0.2500 - val_loss: 0.7563
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4167 - loss: 0.7322 - val_accuracy: 0.2500 - val_loss: 0.7553
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7316 - val_accuracy: 0.2500 - val_loss: 0.7544
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7303 - val_accuracy: 0.2500 - val_loss: 0.7534
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7299 - val_accuracy: 0.2500 - val_loss: 0.7525
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7294 - val_accuracy: 0.2500 - val_loss: 0.7515
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.7286 - val_accuracy: 0.2500 - val_loss: 0.7506
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7274 - val_accuracy: 0.2500 - val_loss: 0.7497
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7268 - val_accuracy: 0.2500 - val_loss: 0.7488
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.7261 - val_accuracy: 0.2500 - val_loss: 0.7480
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7254 - val_accuracy: 0.2500 - val_loss: 0.7471
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7253 - val_accuracy: 0.2500 - val_loss: 0.7463
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7242 - val_accuracy: 0.2500 - val_loss: 0.7454
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7240 - val_accuracy: 0.2500 - val_loss: 0.7446
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7235 - val_accuracy: 0.2500 - val_loss: 0.7437
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7227 - val_accuracy: 0.2500 - val_loss: 0.7429
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7234 - val_accuracy: 0.2500 - val_loss: 0.7421
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7216 - val_accuracy: 0.2500 - val_loss: 0.7413
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7207 - val_accuracy: 0.2500 - val_loss: 0.7405
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7208 - val_accuracy: 0.2500 - val_loss: 0.7397
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7213 - val_accuracy: 0.2500 - val_loss: 0.7390
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7191 - val_accuracy: 0.2500 - val_loss: 0.7382
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7189 - val_accuracy: 0.2500 - val_loss: 0.7374
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7186 - val_accuracy: 0.2500 - val_loss: 0.7367
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7180 - val_accuracy: 0.2500 - val_loss: 0.7359
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7176 - val_accuracy: 0.2500 - val_loss: 0.7352
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.7170 - val_accuracy: 0.2500 - val_loss: 0.7344
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7166 - val_accuracy: 0.2500 - val_loss: 0.7337
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7173 - val_accuracy: 0.2500 - val_loss: 0.7330
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7164 - val_accuracy: 0.2500 - val_loss: 0.7323
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7151 - val_accuracy: 0.2500 - val_loss: 0.7315
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7144 - val_accuracy: 0.2500 - val_loss: 0.7308
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7142 - val_accuracy: 0.2500 - val_loss: 0.7301
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7135 - val_accuracy: 0.2500 - val_loss: 0.7294
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7134 - val_accuracy: 0.2500 - val_loss: 0.7287
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7130 - val_accuracy: 0.2500 - val_loss: 0.7281
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7122 - val_accuracy: 0.2500 - val_loss: 0.7274
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7121 - val_accuracy: 0.2500 - val_loss: 0.7267
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7114 - val_accuracy: 0.5000 - val_loss: 0.7260
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7115 - val_accuracy: 0.5000 - val_loss: 0.7253
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.4167 - loss: 0.7118 - val_accuracy: 0.5000 - val_loss: 0.7246
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4167 - loss: 0.7105 - val_accuracy: 0.5000 - val_loss: 0.7239
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7097 - val_accuracy: 0.5000 - val_loss: 0.7232
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4167 - loss: 0.7096 - val_accuracy: 0.5000 - val_loss: 0.7224
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.4167 - loss: 0.7093 - val_accuracy: 0.5000 - val_loss: 0.7217
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4167 - loss: 0.7084 - val_accuracy: 0.5000 - val_loss: 0.7210
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4167 - loss: 0.7079 - val_accuracy: 0.5000 - val_loss: 0.7203
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.4167 - loss: 0.7086 - val_accuracy: 0.5000 - val_loss: 0.7196
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4167 - loss: 0.7084 - val_accuracy: 0.5000 - val_loss: 0.7189
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.4167 - loss: 0.7080 - val_accuracy: 0.5000 - val_loss: 0.7182
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4167 - loss: 0.7074 - val_accuracy: 0.5000 - val_loss: 0.7174
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.4167 - loss: 0.7061 - val_accuracy: 0.5000 - val_loss: 0.7166
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.4167 - loss: 0.7052 - val_accuracy: 0.5000 - val_loss: 0.7159
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.4167 - loss: 0.7047 - val_accuracy: 0.5000 - val_loss: 0.7151
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.4167 - loss: 0.7046 - val_accuracy: 0.5000 - val_loss: 0.7144
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4167 - loss: 0.7040 - val_accuracy: 0.5000 - val_loss: 0.7136
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.4167 - loss: 0.7036 - val_accuracy: 0.5000 - val_loss: 0.7128
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.4167 - loss: 0.7031 - val_accuracy: 0.5000 - val_loss: 0.7121
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.4167 - loss: 0.7026 - val_accuracy: 0.5000 - val_loss: 0.7113
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.4167 - loss: 0.7021 - val_accuracy: 0.5000 - val_loss: 0.7106

In [15]:
from tensorflow.keras import optimizers

In [17]:
opt=optimizers.SGD(learning_rate=0.01,momentum=0.9)